site_name: rtynerlabs
site_url: https://docs.rtynerlabs.xyz
repo_url: https://github.com/rtyner/mkdocs
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: deep orange
extra:
  copyright: Copyright &copy; 2021 rtynerlabs.xyz
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rtyner
      name: rtyner on GitHub
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.keys
