site_name: rtynerlabs
site_url: https://docs.rtynerlabs.xyz
repo_url: https://github.com/rtyner/mkdocs
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: deep orange
